const livros_biblia_refs= [
    "GEN","EXO","LEV","NUM","DEU","JOS","JDG","RUT","1SA","2SA",
    "1KI","2KI","1CH","2CH","EZR","NEH","EST","JOB","PSA","PRO",
    "ECC","SOL","ISA","JER","LAM","EZE","DAN","HOS","JOE","AMO",
    "OBA","JON","MIC","NAH","HAB","ZEP","HAG","ZEC","MAL","MAT",
    "MAR","LUK","JOH","ACT","ROM","1CO","2CO","GAL","EPH","PHI",
    "COL","1TH","2TH","1TI","2TI","TIT","PHM","HEB","JAM","1PE",
    "2PE","1JO","2JO","3JO","JUD","REV"
];

const livros_biblia = [
    "GÊNESIS","ÊXODO","LEVÍTICO","NÚMEROS","DEUTERONÔMIO",
    "JOSUÉ","JUÍZES","RUTE","I SAMUEL","II SAMUEL",
    "I REIS","II REIS","I CRÔNICAS","II CRÔNICAS","ESDRAS",
    "NEEMIAS","ESTER","JÓ","SALMOS","PROVÉRBIOS","ECLESIASTES",
    "CANTARES","ISAÍAS","JEREMIAS","LAMENTAÇÕES","EZEQUIEL","DANIEL",
    "OSÉIAS","JOEL","AMÓS","OBADIAS","JONAS","MIQUÉIAS","NAUM",
    "HABACUQUE","SOFONIAS","AGEU","ZACARIAS","MALAQUIAS","MATEUS",
    "MARCOS","LUCAS","JOÃO","ATOS","ROMANOS","I CORÍNTIOS","II CORÍNTIOS",
    "GÁLATAS","EFÉSIOS","FILIPENSES","COLOSSENSES","I TESSALONICENSES",
    "II TESSALONICENSES","I TIMÓTEO","II TIMÓTEO","TITO","FILEMON",
    "HEBREUS","TIAGO","I PEDRO","II PEDRO","I JOÃO","II JOÃO",
    "III JOÃO","JUDAS","APOCALIPSE"
];


